# Generated by Django 3.2.7 on 2021-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_auto_20210916_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
